version: '3.8'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222" # Monitoring (optional)
    command: "--jetstream" # Enable JetStream for persistence (optional)
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_user
    ports:
      - "5432:5432"
