export enum Permission {
  VIEW_STORE = 'VIEW_STORE',
  MANAGE_USERS = 'MANAGE_USERS',
  VIEW_INVENTORY = 'VIEW_INVENTORY',
  EDIT_INVENTORY = 'EDIT_INVENTORY',
  VIEW_ORDERS = 'VIEW_ORDERS',
  EDIT_ORDERS = 'EDIT_ORDERS',
}
